
gitlab_app_name: "gitlab-ce"

namespaces:
  - name: gitlab-ce

gitlab:
  namespace: gitlab-ce
  version: gitlab-15.8.5
  route: '<gitlab-fqdn>'
  sso:
    host: 'https://<sso-fqdn>'
    label: 'RH SSO'
    realm: 'devspaces'
    client:
      identifier: 'gitlab-client'
      secret: 'DevSpacesLab2023'
  root_password: '7aydhn160bOrrsGEbnd172rE'
  db_user: 'db_user'
  db_pass: 'db_password'
  db_admin_pass: 'db_admin_passwd'
  db_name: 'gitlabhq_production'
  imagestreams:
    - name: "gitlab-ce"
      tag_name: "gitlab-15.8.5"
      stream_uri: "gitlab/gitlab-ce:15.8.5-ce.0"
    - name: "gitlab-ce-redis"
      tag_name: "5.0.4"
      stream_uri: "redis:5.0.4-alpine"
    - name: "postgresql"
      tag_name: "latest"
      stream_uri: "registry.redhat.io/rhscl/postgresql-13-rhel7"

