---

- hosts: localhost
  tasks:
    - name: Create and Import git project to GitLab
      community.general.gitlab_project:
        api_url: "{{ api_url }}"
        api_username: "{{ api_username }}"
        api_password: "{{ api_password }}" 
        name: summit-lab-2023
        import_url: https://github.com/rht-labs-events/summit-lab-2023 
        visibility: public
        state: present
