apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: checluster
  namespace: openshift-gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: devspaces
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      recurse: true
    path: deploy/lab-content/devspaces 
    repoURL: https://github.com/rht-labs-events/summit-lab-2023.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    managedNamespaceMetadata:
      labels:
        argocd.argoproj.io/managed-by: openshift-gitops
    syncOptions:
    - CreateNamespace=true
