apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
  name: devspaces
  namespace: openshift-gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: openshift-operators
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      recurse: true
    path: deploy/lab-content/operators/devspaces
    repoURL: https://github.com/rht-labs-events/summit-lab-2023.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
