apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitlab
  namespace: openshift-gitops
spec:
  destination:
    namespace: gitlab-system
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      recurse: true
    path: deploy/lab-content/operators/gitlab 
    repoURL: https://github.com/rht-labs-events/summit-lab-2023.git
    targetRevision: main
  syncPolicy:
    managedNamespaceMetadata:
      labels:
        argocd.argoproj.io/managed-by: openshift-gitops
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
