---
kind: Application
apiVersion: argoproj.io/v1alpha1
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-9"
  name: rhsso-operator
  namespace: openshift-gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: devspaces-lab-sso
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      recurse: true
    path: deploy/lab-content/operators/rhsso
    repoURL: https://github.com/rht-labs-events/summit-lab-2023.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    managedNamespaceMetadata:
      labels:
        argocd.argoproj.io/managed-by: openshift-gitops
    syncOptions:
    - CreateNamespace=true
