---
kind: KeycloakUser
apiVersion: keycloak.org/v1alpha1
metadata:
  name: user-lab1
  namespace: devspaces-lab-sso
  finalizers:
    - user.cleanup
  labels:
    app: devspaces-lab-sso-user-lab1
spec:
  realmSelector:
    matchLabels:
      app: devspaces-lab-sso
  user:
    credentials:
      - type: password
        value: DevSpacesLab2023
    email: lab1@example.com
    enabled: true
    firstName: Lab
    lastName: One
    username: lab1

