{{- if .Values.gitlab.cacert }}
apiVersion: v1
data:
  ca-cert.crt: "{{ .Values.gitlab.cacert }}"
kind: Secret
metadata:
  name: gitlab-ca
  namespace: "{{ $.Values.gitlab.namespace }}"
type: Opaque
{{- end }}
