kind: Subscription
apiVersion: operators.coreos.com/v1alpha1
metadata:
  labels:
    operators.coreos.com/devspaces.openshift-operators: ""
  name: devspaces
  namespace: openshift-operators
spec:
  channel: stable
  installPlanApproval: Automatic
  name: devspaces
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  startingCSV: devspacesoperator.v3.5.0
